<?php if (isset($_SESSION['flash'])): ?>
    <p class="bg-info"><?= $_SESSION['flash'] ?></p>
    <?php unset($_SESSION['flash']) ?>
<?php endif ?>

<div>

    <div class="padded">
        <form class="form-inline" method="post" action="/varnish">
            <div class="form-group">
                <label for="exampleInputName2">IP</label>
                <input type="text" name="ip" class="form-control" id="exampleInputName2"
                       placeholder="192.168.0.1">
            </div>
            <button type="submit" class="btn btn-primary">Add Varnish</button>
        </form>
    </div>

    <div class="padded">
        <h1>Varnish Assignments</h1>
    </div>

    <?php foreach ($this->getVarnishes() as $varnish): /** @var \Snowdog\DevTest\Model\Varnish $varnish */ ?>
        <?php $websiteIds = $this->getAssignedWebsiteIds($varnish) ?>
        <h2><?= $varnish->getIP() ?></h2>

        <div class="padded">
            <table class="table table-striped">
                <tr>
                    <th>Associated</th>
                    <th>Name</th>
                    <th>Hostname</th>
                </tr>
                <?php foreach ($this->getWebsites() as $website): /** @var \Snowdog\DevTest\Model\Website $website */ ?>
                    <tr>
                        <td><input class="assoc" value="<?= $varnish->getVarnishId() ?>,<?= $website->getWebsiteId() ?>" type="checkbox" <?= in_array($website->getWebsiteId(), $websiteIds) ? 'checked="checked"' : '' ?>/></td>
                        <td><?= $website->getName() ?></td>
                        <td><?= $website->getHostname() ?></td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>

    <?php endforeach; ?>
</div>