<?php /** @var \Snowdog\DevTest\Controller\VarnishesAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Varnishes - Cache Warmer</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div id="ajax-list" class="container">
    <?php require 'varnish_list.phtml'; ?>
</div><!-- /.container -->
<script>
    $(document).ready(function() {
        $(document).on('click', '.assoc', function(){
            var type = 0;
            if($(this).prop('checked')) {
                type = 1;
            }
            var data = $(this).val() + ',' + type;
            $.ajax({
                method: "POST",
                url: "/varnish-link",
                data: {assoc: data.split(',', 3)}
            }).done(function(data) {
                $('#ajax-list').html(data);
            });
        });
    });
</script>

</body>
</html>